name: Generator

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      download:
        description: Download a fresh OSM dump
        type: boolean
        default: true

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "deploy"
  cancel-in-progress: false

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Restore OSM dump cache
        if: ${{ !inputs.download }}
        uses: actions/cache@v4
        with:
          path: planet-notes-latest.osn
          key: osm-notes-dump

      - name: Download OSM notes dump  & Extract
        if: ${{ inputs.download || !hashFiles('planet-notes-latest.osn') }}
        run: |
          curl -L --fail \
            https://planet.openstreetmap.org/notes/planet-notes-latest.osn.bz2 \
            | bzip2 -dc > planet-notes-latest.osn

      - name: Check size
        run: ls -lh planet-notes-latest.osn

      - name: Run parser
        run: python3 src/parser.py

      - name: Upload notes
        uses: actions/upload-artifact@v7.0.1
        with:
          name: parser-output
          path: |
            notes.bin
          retention-days: 3

  analysis:
    needs: download
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Download Artifact
        uses: actions/download-artifact@v8.0.1
        with:
          name: parser-output

      - name: Find duplicates
        run: python3 src/generator.py

      - name: Upload duplicates
        uses: actions/upload-artifact@v7.0.1
        with:
          name: dupl-notes
          path: dupl_notes.json
          retention-days: 1

  deploy:
    needs: 
      - analysis
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Download duplicates
        uses: actions/download-artifact@v8.0.1
        with:
          name: dupl-notes

      - name: Download boundaries
        run: curl -o osm-countries.geojson https://osm-countries-geojson.monicz.dev/osm-countries-0-01.geojson

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate pages
        run: python3 src/by_countries.py

      - name: Setup Pages
        uses: actions/configure-pages@v6.0.0

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5.0.0
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5

